name: ESP32 Release

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  release:
    name: Build & Release for ESP32-S3
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create GitHub Releases
      id-token: write # Required for AWS OIDC authentication
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30 # stable

      - name: Install espup
        run: cargo install espup --locked
        env:
          RUSTUP_TOOLCHAIN: stable

      - name: Install ESP toolchain
        run: espup install --targets esp32s3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up swap space
        uses: pierotofy/set-swap-space@fc79b3f67fa8a838184ce84a674ca12238d2c761 # master
        with:
          swap-size-gb: 10

      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Install cargo-espflash
        run: cargo install cargo-espflash --locked
        env:
          RUSTUP_TOOLCHAIN: stable

      - name: Build for ESP32-S3
        run: |
          source $HOME/export-esp.sh
          cargo build --release --verbose

      - name: Generate Firmware Bin
        run: |
          source $HOME/export-esp.sh
          cargo espflash save-image --release --chip esp32s3 firmware.bin

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(grep -m1 '^version =' Cargo.toml | cut -d '"' -f2)
          # Create a unique tag using the Cargo version and the short commit SHA
          TAG="v${VERSION}_${GITHUB_SHA::7}"
          
          # Use GitHub CLI to create the release, upload firmware.bin, and generate notes
          gh release create "$TAG" firmware.bin \
            --title "Release $TAG" \
            --generate-notes \
            --target "$GITHUB_SHA"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ff717079ee2060e4bcee96c4779b553acc87447c # v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/esp32-ztp-github-actions-role
          aws-region: eu-central-1

      - name: Upload Firmware to S3 (Triggers OTA)
        run: |
          VERSION=$(grep -m1 '^version =' Cargo.toml | cut -d '"' -f2)
          aws s3 cp firmware.bin s3://esp32-ztp-firmware-${{ secrets.AWS_ACCOUNT_ID }}/firmware_v${VERSION}_${{ github.sha }}.bin
